name: Log Commit Message

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  log-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the commit message
        id: commit
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
      - name: Log commit message
        uses: Ashutoshbind15/commit-logger@nodeenv
        with:
          COMMIT_MESSAGE: ${{ steps.commit.outputs.message }}
        env:
          GEMINI_PRO_API_KEY: ${{ secrets.GEMINI_PRO_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
